// src/lib/mockData.ts

import { MedicalRecord, Alert, Doctor } from '@/types';

export const mockRecords: MedicalRecord[] = [
  {
    id: 'rec-1',
    type: 'Blood Report',
    date: '2024-10-05',
    doctor: 'Dr. Rajesh Sharma',
    clinic: 'City Hospital, Delhi',
    findings: 'All parameters within normal range. Hemoglobin: 14.2 g/dL, WBC: 7500/μL, Blood Glucose: 95 mg/dL (Fasting)',
    status: 'Normal',
  },
  {
    id: 'rec-2',
    type: 'Prescription',
    date: '2025-10-03',
    doctor: 'Dr. Priya Patel',
    clinic: 'Apollo Health Clinic, Mumbai',
    findings: 'Prescribed medication for hypertension management: Amlodipine 5mg (once daily), Metoprolol 25mg (twice daily). Review after 2 weeks.',
    status: 'Reviewed',
  },
  {
    id: 'rec-3',
    type: 'Consultation',
    date: '2025-10-01',
    doctor: 'Dr. Amit Kumar',
    clinic: 'Wellness Medical Center, Bangalore',
    findings: 'General health checkup. Blood pressure: 135/88 mmHg (slightly elevated). Weight: 78 kg, BMI: 26.5 (overweight). Advised regular exercise, reduce salt intake, and stress management.',
    status: 'Reviewed',
  },
  {
    id: 'rec-4',
    type: 'Scan',
    date: '2025-09-28',
    doctor: 'Dr. Suresh Reddy',
    clinic: 'Max Diagnostics, Hyderabad',
    findings: 'Chest X-Ray: Clear lung fields, no abnormalities detected. Heart size normal. No signs of infection or masses.',
    status: 'Normal',
  },
  {
    id: 'rec-5',
    type: 'Blood Report',
    date: '2025-09-15',
    doctor: 'Dr. Neha Gupta',
    clinic: 'Fortis Diagnostics, Pune',
    findings: 'Lipid Profile: Total Cholesterol: 195 mg/dL, LDL: 120 mg/dL, HDL: 45 mg/dL, Triglycerides: 150 mg/dL. Borderline high cholesterol.',
    status: 'Reviewed',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'High Risk',
    date: '2025-10-05',
    title: {
      English: 'High Blood Pressure Alert',
      Hindi: 'उच्च रक्तचाप चेतावनी',
    },
    summary: {
      English: 'Your recent blood pressure reading is above normal range.',
      Hindi: 'आपका हाल का रक्तचाप सामान्य सीमा से अधिक है।',
    },
    details: {
      English: 'Your blood pressure reading of 135/88 mmHg is slightly elevated. Normal blood pressure is below 120/80 mmHg. Please consult your doctor and follow prescribed medication. Monitor your blood pressure regularly and maintain a healthy lifestyle.',
      Hindi: 'आपका रक्तचाप 135/88 mmHg है जो थोड़ा बढ़ा हुआ है। सामान्य रक्तचाप 120/80 mmHg से नीचे होता है। कृपया अपने डॉक्टर से परामर्श करें और निर्धारित दवा लें। नियमित रूप से अपने रक्तचाप की निगरानी करें और स्वस्थ जीवनशैली बनाए रखें।',
    },
  },
  {
    id: 'alert-2',
    type: 'Advisory',
    date: '2025-10-04',
    title: {
      English: 'Medication Reminder',
      Hindi: 'दवा अनुस्मारक',
    },
    summary: {
      English: 'Time to take your prescribed medication - Amlodipine 5mg',
      Hindi: 'अपनी निर्धारित दवा लेने का समय - एम्लोडिपाइन 5mg',
    },
    details: {
      English: 'Please take your Amlodipine 5mg tablet as prescribed by Dr. Priya Patel. Take one tablet daily in the morning after breakfast. Do not skip doses for effective blood pressure control.',
      Hindi: 'कृपया डॉ. प्रिया पटेल द्वारा निर्धारित एम्लोडिपाइन 5mg की गोली लें। नाश्ते के बाद सुबह एक गोली लें। प्रभावी रक्तचाप नियंत्रण के लिए खुराक न छोड़ें।',
    },
  },
  {
    id: 'alert-3',
    type: 'Guidance',
    date: '2025-10-03',
    title: {
      English: 'Cholesterol Level Attention',
      Hindi: 'कोलेस्ट्रॉल स्तर पर ध्यान',
    },
    summary: {
      English: 'Your cholesterol levels are borderline high.',
      Hindi: 'आपका कोलेस्ट्रॉल स्तर सीमा रेखा पर है।',
    },
    details: {
      English: 'Your recent lipid profile shows borderline high cholesterol (195 mg/dL) and LDL (120 mg/dL). Recommended actions: Reduce saturated fat intake, increase fiber-rich foods, exercise 30 minutes daily, and schedule a follow-up test in 3 months.',
      Hindi: 'आपके हाल के लिपिड प्रोफाइल में सीमा रेखा उच्च कोलेस्ट्रॉल (195 mg/dL) और LDL (120 mg/dL) दिखाया गया है। अनुशंसित कार्य: संतृप्त वसा का सेवन कम करें, फाइबर युक्त खाद्य पदार्थ बढ़ाएं, प्रतिदिन 30 मिनट व्यायाम करें, और 3 महीने में फॉलो-अप टेस्ट करवाएं।',
    },
  },
  {
    id: 'alert-4',
    type: 'Advisory',
    date: '2025-10-01',
    title: {
      English: 'Weight Management Suggestion',
      Hindi: 'वजन प्रबंधन सुझाव',
    },
    summary: {
      English: 'Your BMI indicates you are in the overweight category.',
      Hindi: 'आपका BMI दर्शाता है कि आप अधिक वजन वाली श्रेणी में हैं।',
    },
    details: {
      English: 'Your current BMI is 26.5 (overweight range: 25-29.9). Aim to lose 3-5 kg through balanced diet and regular exercise. Recommended: 150 minutes of moderate exercise per week, portion control, and avoid processed foods.',
      Hindi: 'आपका वर्तमान BMI 26.5 है (अधिक वजन सीमा: 25-29.9)। संतुलित आहार और नियमित व्यायाम के माध्यम से 3-5 किलो वजन कम करने का लक्ष्य रखें। अनुशंसित: प्रति सप्ताह 150 मिनट का मध्यम व्यायाम, भाग नियंत्रण, और प्रसंस्कृत खाद्य पदार्थों से बचें।',
    },
  },
];

export const mockDoctors: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Rajesh Sharma',
    type: 'doctor',
    specialty: 'Cardiologist',
    rating: 4.8,
    distance: '2.5 km',
    location: 'South Delhi',
    phone: '+91 98765 43210',
    email: 'dr.sharma@cityhospital.com',
    address: 'City Hospital, Saket, New Delhi - 110017',
    about: 'Dr. Rajesh Sharma is a highly experienced cardiologist with over 15 years of practice. He specializes in preventive cardiology, coronary interventions, and heart disease management. He has performed over 5000 successful cardiac procedures.',
    services: [
      'ECG & Stress Testing',
      'Echocardiography',
      'Coronary Angiography',
      'Heart Disease Management',
      'Preventive Cardiology',
      'Hypertension Treatment',
    ],
  },
  {
    id: 'doc-2',
    name: 'Dr. Priya Patel',
    type: 'doctor',
    specialty: 'General Physician',
    rating: 4.7,
    distance: '1.8 km',
    location: 'Andheri West',
    phone: '+91 98765 43211',
    email: 'dr.patel@apolloclinic.com',
    address: 'Apollo Health Clinic, Andheri West, Mumbai - 400053',
    about: 'Dr. Priya Patel is a dedicated general physician with 12 years of experience in treating various medical conditions. She focuses on preventive healthcare, chronic disease management, and family medicine.',
    services: [
      'General Health Checkup',
      'Chronic Disease Management',
      'Diabetes Care',
      'Hypertension Management',
      'Fever & Infection Treatment',
      'Health Counseling',
    ],
  },
  {
    id: 'doc-3',
    name: 'Dr. Amit Kumar',
    type: 'doctor',
    specialty: 'Diabetologist',
    rating: 4.6,
    distance: '3.2 km',
    location: 'Koramangala',
    phone: '+91 98765 43212',
    email: 'dr.kumar@wellnesscenter.com',
    address: 'Wellness Medical Center, Koramangala, Bangalore - 560034',
    about: 'Dr. Amit Kumar is a renowned diabetologist and endocrinologist with 10 years of expertise in diabetes management and metabolic disorders. He provides comprehensive care for Type 1, Type 2 diabetes, and thyroid disorders.',
    services: [
      'Diabetes Management',
      'Thyroid Disorders',
      'HbA1c Monitoring',
      'Insulin Therapy',
      'Dietary Counseling',
      'Lifestyle Modification',
    ],
  },
  {
    id: 'doc-4',
    name: 'Dr. Suresh Reddy',
    type: 'doctor',
    specialty: 'Radiologist',
    rating: 4.9,
    distance: '4.1 km',
    location: 'Banjara Hills',
    phone: '+91 98765 43213',
    email: 'dr.reddy@maxdiagnostics.com',
    address: 'Max Diagnostics, Banjara Hills, Hyderabad - 500034',
    about: 'Dr. Suresh Reddy is a highly skilled radiologist with 18 years of experience in diagnostic imaging. He specializes in CT, MRI, X-Ray interpretation, and interventional radiology procedures.',
    services: [
      'X-Ray Imaging',
      'CT Scan Analysis',
      'MRI Interpretation',
      'Ultrasound',
      'Mammography',
      'Interventional Radiology',
    ],
  },
  {
    id: 'doc-5',
    name: 'Dr. Neha Gupta',
    type: 'doctor',
    specialty: 'Pathologist',
    rating: 4.5,
    distance: '5.3 km',
    location: 'Kothrud',
    phone: '+91 98765 43214',
    email: 'dr.gupta@fortisdiagnostics.com',
    address: 'Fortis Diagnostics, Kothrud, Pune - 411038',
    about: 'Dr. Neha Gupta is an experienced pathologist with 8 years of expertise in clinical pathology and laboratory medicine. She specializes in blood tests, tissue analysis, and disease diagnosis through laboratory investigations.',
    services: [
      'Blood Testing (CBC, Lipid Profile)',
      'Hormone Analysis',
      'Liver & Kidney Function Tests',
      'Thyroid Function Tests',
      'Biopsy Analysis',
      'Urine & Stool Analysis',
    ],
  },
  {
    id: 'doc-6',
    name: 'Dr. Vikram Singh',
    type: 'doctor',
    specialty: 'Orthopedic Surgeon',
    rating: 4.7,
    distance: '3.8 km',
    location: 'Sector 62',
    phone: '+91 98765 43215',
    email: 'dr.singh@maxhospital.com',
    address: 'Max Super Specialty Hospital, Sector 62, Noida - 201301',
    about: 'Dr. Vikram Singh is a leading orthopedic surgeon with 14 years of experience in joint replacement, sports injuries, and trauma care. He has performed over 3000 successful orthopedic surgeries.',
    services: [
      'Joint Replacement Surgery',
      'Sports Injury Treatment',
      'Fracture Care',
      'Arthroscopy',
      'Spine Surgery',
      'Arthritis Management',
    ],
  },
  {
    id: 'doc-7',
    name: 'Dr. Kavita Rao',
    type: 'doctor',
    specialty: 'Gynecologist',
    rating: 4.8,
    distance: '2.1 km',
    location: 'Jubilee Hills',
    phone: '+91 98765 43216',
    email: 'dr.rao@apollowomens.com',
    address: 'Apollo Women\'s Hospital, Jubilee Hills, Hyderabad - 500033',
    about: 'Dr. Kavita Rao is a renowned gynecologist and obstetrician with 16 years of experience in women\'s health, pregnancy care, and minimally invasive gynecological surgeries.',
    services: [
      'Prenatal Care',
      'High-Risk Pregnancy',
      'Gynecological Surgery',
      'Fertility Treatment',
      'Menopause Management',
      'Family Planning',
    ],
  },
  {
    id: 'doc-8',
    name: 'Dr. Arun Mehta',
    type: 'doctor',
    specialty: 'Dermatologist',
    rating: 4.6,
    distance: '1.5 km',
    location: 'Marine Lines',
    phone: '+91 98765 43217',
    email: 'dr.mehta@skinclinic.com',
    address: 'Skin & Aesthetic Clinic, Marine Lines, Mumbai - 400002',
    about: 'Dr. Arun Mehta is a board-certified dermatologist with 11 years of experience in medical and cosmetic dermatology. He specializes in skin diseases, acne treatment, and aesthetic procedures.',
    services: [
      'Acne Treatment',
      'Hair Loss Treatment',
      'Skin Allergies',
      'Laser Therapy',
      'Chemical Peels',
      'Anti-Aging Treatments',
    ],
  },
];

// ✅ Export mock chat messages for chatbot
export const mockChatHistory: Array<{
  id: number;
  text: string;
  sender: 'user' | 'ai';
  timestamp: Date;
}> = [
  {
    id: 1,
    text: 'Hello! How can I help you today?',
    sender: 'ai',
    timestamp: new Date('2025-10-06T10:00:00'),
  },
  {
    id: 2,
    text: 'I have a question about my blood pressure readings',
    sender: 'user',
    timestamp: new Date('2025-10-06T10:01:00'),
  },
  {
    id: 3,
    text: 'I\'d be happy to help! Your recent reading shows 135/88 mmHg, which is slightly elevated. Normal blood pressure is below 120/80 mmHg. I recommend: 1) Continue your prescribed medication, 2) Reduce salt intake, 3) Exercise regularly, 4) Monitor daily.',
    sender: 'ai',
    timestamp: new Date('2025-10-06T10:02:00'),
  },
];