version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/ayu-raksha-frontend

permissions:
  - object: /var/www/ayu-raksha-frontend
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu