version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
      - npm install --legacy-peer-deps
      - npm install zustand --legacy-peer-deps  # ✅ Explicitly install zustand

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - node --version
      - npm --version
      - echo "Verifying zustand installation..."
      - npm list zustand || echo "Zustand not found!"

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Post-build phase completed"
      - echo "Build artifact size:"
      - du -sh .next/ || echo ".next directory not found"

artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.mjs'
    - 'appspec.yml'
    - 'scripts/**/*'
  name: ayu-raksha-frontend-build
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'