version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'pages/**/*'
    - 'app/**/*'
    - 'components/**/*'
    - 'public/**/*'
    - '.next/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
    - 'next.config.mjs'
    - 'appspec.yml'
    - 'scripts/**/*'
  discard-paths: no