version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - node --version
      - npm --version

  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - echo "Build completed successfully"
      - echo "Creating standalone build..."
      - ls -la .next/

  post_build:
    commands:
      - echo "Post-build phase completed"
      - echo "Build artifact size:"
      - du -sh .next/

artifacts:
  files:
    - '.next/**/*'
    - 'public/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'next.config.js'
    - 'next.config.mjs'
    - 'appspec.yml'
    - 'scripts/**/*'
  name: ayu-raksha-frontend-build
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*'